### ISSUE TITLE
License issue: MuPDF is GNU AGPL licensed

### ISSUE THREAD

**Issue by robinwatts** [evandenberg/mupdf-viewer#6]
MuPDF is GNU AGPL licensed. You cannot have your code under the MIT license given it includes compiled MuPDF binaries.

Please comply with the GNU AGPL or remove this repo.

Thanks.

**Comment by evandenberg** [comment]
Thank you for bringing this to my attention. I've updated the license to GNU AGPL.

**Comment by robinwatts** [comment]
Thanks!

(It might be nice to say exactly what version of the lib you're using to make it easier for people to recompile).
